'use client';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation, Pagination, Mousewheel, Keyboard } from 'swiper/modules';
import 'swiper/css'; 'swiper/css/navigation'; 'swiper/css/pagination';

export default function TutoratCollaboratif() {
  return (
    <div style={{ fontFamily: "'Poppins', sans-serif", height: '100vh', overflow: 'hidden', background: 'linear-gradient(135deg, #1a2a3a 0%, #0f1f2f 50%, #0a1f2f 100%)', color: '#e0e0e0' }}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;700;800&display=swap'); .swiper { width: 100%; height: 100vh; } .swiper-slide { display: flex; align-items: center; justify-content: center; padding: 60px; } .swiper-button-next, .swiper-button-prev { color: #3498DB !important; background: rgba(52, 152, 219, 0.2); width: 50px; height: 50px; border-radius: 50%; backdrop-filter: blur(10px); } .swiper-button-next:after, .swiper-button-prev:after { font-size: 20px; } .swiper-pagination-bullet { background: rgba(255, 255, 255, 0.3); width: 12px; height: 12px; } .swiper-pagination-bullet-active { background: #3498DB; box-shadow: 0 0 15px rgba(52, 152, 219, 0.6); } .swiper-pagination { bottom: 30px !important; left: 50% !important; transform: translateX(-50%); width: auto !important; display: flex; flex-direction: row; gap: 10px; }`}</style>
      <Swiper direction="horizontal" slidesPerView={1} spaceBetween={0} mousewheel={true} keyboard={true} pagination={{ clickable: true }} navigation={true} modules={[Navigation, Pagination, Mousewheel, Keyboard]}>
        <SwiperSlide><div style={{ maxWidth: '1200px', width: '100%' }}><a href="/" style={{ color: '#3498DB', fontSize: '1rem', marginBottom: '40px', display: 'inline-block', textDecoration: 'none' }}>← Retour</a><h1 style={{ fontSize: '4.5rem', fontWeight: 800, background: 'linear-gradient(135deg, #3498DB 0%, #2980B9 100%)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', marginBottom: '30px' }}>🤝 Tutorat Collaboratif</h1><p style={{ fontSize: '1.5rem', color: '#5DADE2', lineHeight: 1.8, maxWidth: '800px' }}>Mise en relation intelligente pairs + experts basée sur compétences et besoins</p></div></SwiperSlide>
        <SwiperSlide><div style={{ maxWidth: '1200px', width: '100%' }}><h2 style={{ color: '#3498DB', fontSize: '3em', marginBottom: '40px' }}>🔄 Matching Intelligent</h2><div style={{ background: 'rgba(0, 0, 0, 0.3)', padding: '50px', borderRadius: '20px', fontFamily: 'monospace', color: '#5DADE2', lineHeight: 2, fontSize: '1.1em' }}><pre style={{ margin: 0 }}>{`🎯 ALGORITHME MATCHING\n\n1️⃣ Profil Compétences (DuckDB)\n   • Skills maîtrisées (niveau 1-5)\n   • Lacunes identifiées\n   • Style apprentissage\n   • Disponibilités\n\n2️⃣ Matching Multi-Critères\n   • Complémentarité compétences\n   • Compatibilité style pédagogique\n   • Proximité géographique (optionnel)\n   • Évaluations pairs (rating)\n\n3️⃣ Mise en Relation\n   • Proposition binôme tuteur/apprenant\n   • Objectifs session définis\n   • Outils collaboratifs (whiteboard IA)\n\n4️⃣ Feedback & Amélioration\n   • Rating mutuel post-session\n   • Amélioration continue matching\n   • Badges gamification`}</pre></div></div></SwiperSlide>
        <SwiperSlide><div style={{ maxWidth: '1200px', width: '100%', textAlign: 'center' }}><h2 style={{ color: '#3498DB', fontSize: '3em', marginBottom: '40px' }}>🤝 Tutorat Pair-à-Pair</h2><p style={{ fontSize: '1.3rem', color: '#5DADE2', lineHeight: 1.8, maxWidth: '700px', margin: '0 auto 50px' }}>Matching intelligent pour sessions tutoring efficaces et enrichissantes</p><div style={{ background: 'linear-gradient(135deg, rgba(52, 152, 219, 0.15) 0%, rgba(93, 173, 226, 0.15) 100%)', padding: '40px', borderRadius: '20px', border: '2px solid rgba(52, 152, 219, 0.3)', maxWidth: '600px', margin: '0 auto' }}><h3 style={{ color: '#3498DB', marginBottom: '25px', fontSize: '1.5em' }}>💡 Résultats</h3><ul style={{ color: '#c0c0c0', lineHeight: 2.2, paddingLeft: '25px', fontSize: '1.1em', textAlign: 'left' }}><li><strong style={{ color: '#3498DB' }}>Matching:</strong> 88% satisfaction binômes</li><li><strong style={{ color: '#3498DB' }}>Apprentissage:</strong> +34% rétention (vs seul)</li><li><strong style={{ color: '#3498DB' }}>Social:</strong> Réseau entraide pérenne</li></ul></div><div style={{ marginTop: '50px' }}><a href="/" style={{ background: 'linear-gradient(135deg, #3498DB 0%, #2980B9 100%)', color: '#fff', padding: '15px 40px', borderRadius: '30px', textDecoration: 'none', fontSize: '1.1em', fontWeight: 700, display: 'inline-block' }}>Retour</a></div></div></SwiperSlide>
      </Swiper>
    </div>
  );
}
